server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
    
eureka:
  client:
    #表示是否将自己注册进入eurekaServer,默认为true
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka